### ISSUE TITLE
内容小错误

### ISSUE THREAD

**Issue by taseikyo** [JoshuaShuo77/Cpp17#3]
在 [9.1 编译期if语句产生的原因](https://github.com/JoshuaShuo77/Cpp17/blob/master/Chapter9-%E7%BC%96%E8%AF%91%E6%9C%9Fif%E8%AF%AD%E5%8F%A5.md#91-%E7%BC%96%E8%AF%91%E6%9C%9Fif%E8%AF%AD%E5%8F%A5%E4%BA%A7%E7%94%9F%E7%9A%84%E5%8E%9F%E5%9B%A0) 有个小错误，可能是打字笔误：
![20200923155453](https://user-images.githubusercontent.com/23132915/93983609-5ed2c280-fdb5-11ea-8cd0-b679cda3308c.png)
应该是：

```C++
if (std::is_same_v<T, std::string>) {
    return x;
}
```

**Comment by JoshuaShuo77** [comment]
已经修正
